CREATE DATABASE IF NOT EXISTS yuliv_db;
use yuliv_db;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    pincode VARCHAR(10)
);

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS inventory;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE inventory (
id int AUTO_INCREMENT PRIMARY KEY,
EAN_CODE VARCHAR(100) NOT NULL,
PRODUCT_NAME VARCHAR(100),
PRODUCT_PRICE INT,
SELLING_PRICE INT,
DISCOUNT FLOAT,
INVENTORY_QTY INT
);

CREATE TABLE IF NOT EXISTS cart_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (medicine_id) REFERENCES inventory(id)
);
/*insert into inventory (EAN_CODE, PRODUCT_NAME, PRODUCT_PRICE, SELLING_PRICE, DISCOUNT, INVENTORY_QTY)
values 
(89046731631, 'MAMAEARTH UBTAN FACEWASH 100ML_269', 269, 269, 10, 20),
(89046731632, 'MAMAEARTH VITAMIN C FACEWASH 100ML_269', 269, 269, 10, 20);*/
LOAD DATA local INFILE '/Users/muruganandan/Documents/programs/inventory.csv'
into table inventory
fields terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 rows
(EAN_CODE, PRODUCT_NAME, PRODUCT_PRICE, SELLING_PRICE, DISCOUNT, INVENTORY_QTY);
select EAN_CODE,PRODUCT_NAME,INVENTORY_QTY FROM INVENTORY WHERE INVENTORY_QTY <=10 OR INVENTORY_QTY IS NULL;
